name: 🐞 Bug report
description: Create a bug report to help us improve
labels: [ "bug", "status/0-triage", "priority/p0" ]
body:
  - type: markdown
    attributes:
      value: |
        **Thanks for helping us to improve Packer!**

        We welcome all bugs reports. Please fill out each area of the form so we can better help you.
        If you are reporting, make sure that we do not have any duplicates already open.
        You can ensure this by searching the [issue list](https://github.com/sentinelos/packer/issues?q=is:issue+label:bug) for this repository.
        If there is a duplicate, please close your issue and add a comment to the existing issue instead.
        
        ---
  - type: checkboxes
    attributes:
      label: Packer architecture
      description: Current supporting architectures
      options:
        - label: linux/amd64 (x86_64)
        - label: linux/arm64 (aarch64)
    validations:
      required: true
  - type: input
    attributes:
      label: Packer version
      description: Output of `packer version`
    validations:
      required: true
  - type: input
    attributes:
      label: Our host architecture
      description: Output of `uname -a`
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: Also tell us more about bug
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the bug issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: By submitting this bug issue, you agree to follow our [Code of Conduct](https://github.com/sentinelos/packer/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this repository Code of Conduct
          required: true